### ISSUE TITLE
Chrome Version + Advice

### ISSUE THREAD

**Issue by achernob** [9b/google-alerts#26]
Hi Brandon - I have two quick follow up questions ..wasn't sure whether I should start a new thread for the second since only the first one is a bug.

1) When trying to seed a login through the command prompt, I am getting the following error: "Chrome version must be between 71 and 75." I suppose I could back date my chrome version (77 right now), but is there a more permanent solution? I presume that other folks will run into this soon as well since Chrome typically auto-updates. 

2) I'm a beginner, so sorry in advance if this is a silly question. About a month ago (before my Chrome updated, I guess) I was successfully seeding a session and also creating alerts on a given account strictly using the command prompt. This helped me understand how to do everything from the command prompt itself. My code, however, runs through a spreadsheet, creates a dictionary of a bunch of alerts to create for several users, and then logs into each account to create them in Python. I was originally able to do this without the command prompt (since seeding a session wasn't necessary - this is going back about a year now probably). Now, I somehow need to call the command prompt from my Python script to seed a session in the middle of my script when I am ready to upload that person's alerts. I tried to understand how to do this using the web, but haven't found a way to do it. To simplify the question, suppose you have a recently created dictionary from an Excel workbook, where the alerts are in each row (e.g. Row 1: "Tesla -Musk -Stock"; Row 2: "Ford - GM; etc) and you have the user's login credentials. How would you then (1) call the command prompt to seed that user's session, (2) create all the alerts (still in command prompt?), and (3) exit out of the session / seed the next user.

Thank you SO much! This has been incredibly helpful and I deeply appreciate your help and advice.

**Comment by 9b** [comment]
Thanks for using the library and filing issues when you find them.

1. I can't really control Chrome or the requirements they dictate. The driver website offers back-dated versions, so it shouldn't be an issue to nab one of those and seed the session. I just tested my versions and it all worked okay. 

2. Seeding unfortunately uses Selenium in conjunction with the CLI, so there's not many options to fully automate the process. This is just due to Google not wanting bots to script their login process––seeding through Selenium appears less like a bot and therefore is a viable method. For your use case, I would just consider baking in some canary checks that test when a session has died, and then prompts you to run the flow again. The sessions last pretty long, so you shouldn't need to update all the time. I know it's not a perfect solution, but this library is very much a hack. :)

**Comment by achernob** [comment]
Thank you! Very helpful. I will backdate on #1. On the second point, are
you able to give any advice on how to seed a session from a Python script?
Like I said, I think this is an elementary problem but I can't seem to
figure it out. I'm using IDLE and somehow need to bring up the command
prompt and feed commands through it mid session...any advise? Thank you
very much!

**Comment by 9b** [comment]
I think the best I could help is to point you to the seed function code that I use within my CLI tool. You can see the function here which is pretty easy to follow, https://github.com/9b/google-alerts/blob/master/google_alerts/cli/manage.py#L117
